var activitiesData =
{"type":"FeatureCollection","features":[
{"type": "Feature","properties":{"title":"De gouden kerk van Sao Francisco da Penitencia","rank":7,"activity":"architecture"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-22.9066434,-43.180346]}}
{"type": "Feature","properties":{"title":"Las Lajas Sanctuary","rank":8,"activity":"architecture"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[0.8053343,-77.585998]}}
{"type": "Feature","properties":{"title":"Python Bridge","rank":7,"activity":"architecture"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[52.37302,4.94893]}}
{"type": "Feature","properties":{"title":"Henderson Waves Bridge","rank":1,"activity":"architecture"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[1.2801016,103.8029949]}}
{"type": "Feature","properties":{"title":"Paardrijden met Gauchos ","rank":7,"activity":"bbirds"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-50.9423262,-73.406788]}}
{"type": "Feature","properties":{"title":"Daal af in een vulkaan","rank":8,"activity":"bbirds"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[63.97114026,-21.61834717]}}
{"type": "Feature","properties":{"title":"Son Doong Cave","rank":8,"activity":"bbirds"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[17.6102715,106.3487474]}}
{"type": "Feature","properties":{"title":"s Werelds langste schommel ","rank":8,"activity":"bungee"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-45.0479034,168.6850109]}}
{"type": "Feature","properties":{"title":"Aapjes kijken op Borneo","rank":8,"activity":"wildlife"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[5.8765447,117.9505641]}}
{"type": "Feature","properties":{"title":"Glowworm Cave","rank":8,"activity":"wildlife"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-38.260748,175.103986]}}
{"type": "Feature","properties":{"title":"The Big Five","rank":9,"activity":"wildlife"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-30.559482,22.937506]}}
{"type": "Feature","properties":{"title":"Zwem tussen miljoenen kwallen (zonder geprikt te worden)","rank":8,"activity":"wildlife"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[7.51498,134.58252]}}
{"type": "Feature","properties":{"title":"Aogashima","rank":8,"activity":"islands"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[32.4583368,139.7688449]}}
{"type": "Feature","properties":{"title":"Socotra Island","rank":7,"activity":"islands"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[12.4634205,53.8237385]}}
{"type": "Feature","properties":{"title":"Carnival Rio","rank":8,"activity":"festival"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-22.9068467,-43.1728965]}}
{"type": "Feature","properties":{"title":"Tapati Rapa Nui festival op Paaseiland","rank":8,"activity":"festival"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-27.0889845,-109.354527]}}
{"type": "Feature","properties":{"title":"Oktoberfest","rank":7,"activity":"festival"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[48.1351253,11.5819806]}}
{"type": "Feature","properties":{"title":"International highline meeting festival - Monte Piana","rank":1,"activity":"festival"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[46.5819419,12.2519214]}}
{"type": "Feature","properties":{"title":"Songkran (Thai's nieuwjaar) - Chiang Mai","rank":1,"activity":"festival"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[18.7060641,98.9817163]}}
{"type": "Feature","properties":{"title":"Full Moon - Koh Phangan","rank":1,"activity":"festival"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[9.7318753,100.0135929]}}
{"type": "Feature","properties":{"title":"Burning Man festival ","rank":9,"activity":"festival"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[40.910733,-119.0560102]}}
{"type": "Feature","properties":{"title":"Mardi Gras","rank":8,"activity":"festival"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[29.9510658,-90.0715323]}}
{"type": "Feature","properties":{"title":"Bierbrouwerijen / biertour","rank":7,"activity":"food"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[51.2026474,3.2246471]}}
{"type": "Feature","properties":{"title":"La Bodeguita del Medio en El Floridita","rank":7,"activity":"food"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[23.1404394,-82.3535985]}}
{"type": "Feature","properties":{"title":"Wijnhuizen / wijntour","rank":8,"activity":"food"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[48.026628,0.333235]}}
{"type": "Feature","properties":{"title":"Currywurst Museum","rank":7,"activity":"food"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[52.5088197,13.3912691]}}
{"type": "Feature","properties":{"title":"Eet als een echte Bedoeïne","rank":8,"activity":"food"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[29.584579,35.426273]}}
{"type": "Feature","properties":{"title":"Hawker stalls in Kuala Lumpur","rank":8,"activity":"food"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[3.146642,101.6958449]}}
{"type": "Feature","properties":{"title":"Vis markt Kota Kinabalu","rank":8,"activity":"food"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[5.980408,116.0734568]}}
{"type": "Feature","properties":{"title":"Mole sauce ","rank":8,"activity":"food"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[23.634501,-102.552784]}}
{"type": "Feature","properties":{"title":"Taros cafe restaurant in Essaouira","rank":9,"activity":"food"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[31.51219,-9.772066]}}
{"type": "Feature","properties":{"title":"Pinchos tour in San Sebastian","rank":7,"activity":"food"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[43.318334,-1.9812313]}}
{"type": "Feature","properties":{"title":"Creps al Born","rank":7,"activity":"food"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[41.3843126,2.1826984]}}
{"type": "Feature","properties":{"title":"The Rabot Estate","rank":7,"activity":"food"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[51.5054388,-0.0899901]}}
{"type": "Feature","properties":{"title":"Ithaa Undersea Restaurant","rank":8,"activity":"food"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[3.6155279,72.7239937]}}
{"type": "Feature","properties":{"title":"Ascensor Artilleria, Valparaiso","rank":7,"activity":"history"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-33.033632,-71.6300142]}}
{"type": "Feature","properties":{"title":"Escobar tour in Medellin","rank":7,"activity":"history"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[4.570868,-74.297333]}}
{"type": "Feature","properties":{"title":"De stenen ballen van Costa Rica","rank":7,"activity":"history"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[8.707268,-83.8817571]}}
{"type": "Feature","properties":{"title":"Koffieplantages","rank":7,"activity":"history"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[20.03,-75.3914]}}
{"type": "Feature","properties":{"title":"Place du Tertre, Parijs","rank":7,"activity":"history"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[48.8864095,2.3405716]}}
{"type": "Feature","properties":{"title":"De Oude Stad van Jeruzalem","rank":8,"activity":"history"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[31.7776563,35.2324593]}}
{"type": "Feature","properties":{"title":"Old Jaffa","rank":7,"activity":"history"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[32.054447,34.753619]}}
{"type": "Feature","properties":{"title":"Masada","rank":7,"activity":"history"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[32.682305,35.597657]}}
{"type": "Feature","properties":{"title":"De Galilee","rank":7,"activity":"history"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[32.9,35.333333]}}
{"type": "Feature","properties":{"title":"Jad Wasjem Holocaust Memorial","rank":8,"activity":"history"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[31.7741936,35.1753018]}}
{"type": "Feature","properties":{"title":"Bunkers del Carmel Barcelona","rank":7,"activity":"history"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[41.420048,2.16269]}}
{"type": "Feature","properties":{"title":"Chapelco Golf Resort","rank":8,"activity":"golfing"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-40.1199438,-71.2432802]}}
{"type": "Feature","properties":{"title":"St. Andrews (Old Course)","rank":7,"activity":"golfing"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[56.3397753,-2.7967214]}}
{"type": "Feature","properties":{"title":"Royal County Down Golf Club","rank":7,"activity":"golfing"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[54.216937,-5.885974]}}
{"type": "Feature","properties":{"title":"Toboggan Ride from Monte to Funchal","rank":7,"activity":"speed"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[32.6717146,-16.9093]}}
{"type": "Feature","properties":{"title":"National Park Corcovado","rank":8,"activity":"jungle"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[8.5367183,-83.3020169]}}
{"type": "Feature","properties":{"title":"Hike langs de Rio Celeste","rank":8,"activity":"jungle"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[10.658282,-84.9713512]}}
{"type": "Feature","properties":{"title":"Viñales","rank":7,"activity":"jungle"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[22.6152778,-83.7158333]}}
{"type": "Feature","properties":{"title":"Saramacca","rank":1,"activity":"jungle"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[3.63403563,-56.29943848]}}
{"type": "Feature","properties":{"title":"Chapada Diamantina","rank":8,"activity":"landscape"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-11.4961111,-41.2730556]}}
{"type": "Feature","properties":{"title":"Valle de Cocora","rank":8,"activity":"landscape"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[4.63735,-75.48667]}}
{"type": "Feature","properties":{"title":"Paardrijden","rank":8,"activity":"landscape"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[10.2749682,-84.8255097]}}
{"type": "Feature","properties":{"title":"Słowiński National Park","rank":7,"activity":"landscape"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[54.7001729,17.3169313]}}
{"type": "Feature","properties":{"title":"Feluccatocht over de Nijl","rank":8,"activity":"locals"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[30.7773321,30.804369]}}
{"type": "Feature","properties":{"title":"Parc des Buttes Chaumont, Parijs","rank":7,"activity":"locals"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[48.8809496,2.3827609]}}
{"type": "Feature","properties":{"title":"Mai Chau tribe","rank":1,"activity":"locals"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[20.6901339,105.0089888]}}
{"type": "Feature","properties":{"title":"Hike up de Corcovado","rank":8,"activity":"mountains"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-22.952352,-43.2114467]}}
{"type": "Feature","properties":{"title":"La Casa Del Arbol","rank":8,"activity":"mountains"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-1.4158477,-78.4262466]}}
{"type": "Feature","properties":{"title":"Bedwing de Rinjani","rank":9,"activity":"mountains"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-8.4112952,116.4573488]}}
{"type": "Feature","properties":{"title":"Kilimanjaro beklimmen","rank":8,"activity":"mountains"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-3.066667,37.359167]}}
{"type": "Feature","properties":{"title":"Cancun Underwater Museum","rank":9,"activity":"museum"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[21.1109,86.7636]}}
{"type": "Feature","properties":{"title":"International Spy Museum","rank":7,"activity":"museum"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[38.8969908,-77.0236404]}}
{"type": "Feature","properties":{"title":"Great Blue Hole","rank":8,"activity":"scuba"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[17.3157608,-87.5348863]}}
{"type": "Feature","properties":{"title":"Duiken rondom Bonito","rank":8,"activity":"scuba"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-21.1286275,-56.4928922]}}
{"type": "Feature","properties":{"title":"De onderwaterwereld van Fernando de Noronha","rank":9,"activity":"scuba"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-3.8576305,-32.4297369]}}
{"type": "Feature","properties":{"title":"Duiken in Isla del Coco","rank":8,"activity":"scuba"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[5.5282283,-87.0574302]}}
{"type": "Feature","properties":{"title":"Duiken in Cocos Island","rank":8,"activity":"scuba"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[5.5282283,-87.0574302]}}
{"type": "Feature","properties":{"title":"Duiken in Diver's Paradise","rank":8,"activity":"scuba"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[12.219569,-68.351998]}}
{"type": "Feature","properties":{"title":"Paragliding in Medellín","rank":8,"activity":"parachute"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[6.244203,-75.5812119]}}
{"type": "Feature","properties":{"title":"Party met locals in grotten in Cuba","rank":7,"activity":"nightlife"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[21.521757,-77.781167]}}
{"type": "Feature","properties":{"title":"Carnaval in Santiago de Cuba","rank":7,"activity":"nightlife"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[20.01693,-75.8301537]}}
{"type": "Feature","properties":{"title":"Sparty in Budapest's Romeinse Baden","rank":8,"activity":"nightlife"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[47.497912,19.040235]}}
{"type": "Feature","properties":{"title":"Tel Aviv 'feesthoofdstad'","rank":8,"activity":"nightlife"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[32.0852999,34.7817676]}}
{"type": "Feature","properties":{"title":"Midzomernacht feest","rank":7,"activity":"nightlife"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[67.87554135,20.24230957]}}
{"type": "Feature","properties":{"title":"Zanzibar, Jan Thiel","rank":8,"activity":"nightlife"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[12.0757545,-68.879444]}}
{"type": "Feature","properties":{"title":"Raften over de rivier van Sarapiqui","rank":8,"activity":"rafting"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[10.473523,-84.0167423]}}
{"type": "Feature","properties":{"title":"Torres del Paine National Park","rank":9,"activity":"winter"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-50.9423262,-73.406788]}}
{"type": "Feature","properties":{"title":"Bavarian Alps","rank":1,"activity":"winter"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[47.5175925,10.9381827]}}
{"type": "Feature","properties":{"title":"Genieten op Jijoca de Jericoacoara","rank":8,"activity":"beach"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-2.7956223,-40.5142274]}}
{"type": "Feature","properties":{"title":"Stranden bij Cabo de la Vela","rank":7,"activity":"beach"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[12.195475,-72.147218]}}
{"type": "Feature","properties":{"title":"Palomino","rank":8,"activity":"beach"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[11.2451212,-73.5593968]}}
{"type": "Feature","properties":{"title":"Cayo Largo del Sur","rank":7,"activity":"beach"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[21.6117789,-81.5288929]}}
{"type": "Feature","properties":{"title":"De eilandengroep Fernando de Noronha","rank":9,"activity":"unesco"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-3.8576305,-32.4297369]}}
{"type": "Feature","properties":{"title":"Honghe Hani Rice Terraces","rank":8,"activity":"unesco"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[25.045806,102.710002]}}
{"type": "Feature","properties":{"title":"Zhangjiajie National Forest Park","rank":9,"activity":"unesco"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[29.3143553,110.4328514]}}
{"type": "Feature","properties":{"title":"Longji Terraces","rank":8,"activity":"unesco"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[25.7257826,110.0723577]}}
{"type": "Feature","properties":{"title":"Hani Terraces","rank":8,"activity":"unesco"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[23.219932,102.835223]}}
{"type": "Feature","properties":{"title":"Tune out op Cocos Island","rank":9,"activity":"unesco"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[5.5282283,-87.0574302]}}
{"type": "Feature","properties":{"title":"Baha’i Gardens in Haifa","rank":7,"activity":"unesco"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[32.8172311,34.9887569]}}
{"type": "Feature","properties":{"title":"Adriatische kust","rank":7,"activity":"villa"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[45.1286455,13.901542]}}
{"type": "Feature","properties":{"title":"Bordeaux","rank":7,"activity":"villa"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[44.837789,-0.57918]}}
{"type": "Feature","properties":{"title":"Bali","rank":9,"activity":"villa"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-8.4095178,115.188916]}}
{"type": "Feature","properties":{"title":"Israel","rank":8,"activity":"villa"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[31.046051,34.851612]}}
{"type": "Feature","properties":{"title":"Canarische Eilanden","rank":7,"activity":"villa"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[29.0468535,-13.5899733]}}
{"type": "Feature","properties":{"title":"Ibiza","rank":7,"activity":"villa"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[39.0200099,1.4821482]}}
{"type": "Feature","properties":{"title":"Rio de Prata","rank":8,"activity":"watersport"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-21.131171,-56.4831814]}}
{"type": "Feature","properties":{"title":"Kajakken door de junglekanalen van Caño Negro","rank":8,"activity":"watersport"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[10.89241,-84.79567]}}
{"type": "Feature","properties":{"title":"Wipe-out baan op Koh Phangan ","rank":7,"activity":"watersport"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[9.7318753,100.0135929]}}
{"type": "Feature","properties":{"title":"Vouliagmeni meer Athene","rank":8,"activity":"wellness"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[37.8216582,23.7754127]}}
{"type": "Feature","properties":{"title":"Drijf in de Dode Zee ","rank":1,"activity":"wellness"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[31.5590287,35.4731895]}}
{"type": "Feature","properties":{"title":"The Dhara Dhevi Chiang Mai Resort","rank":1,"activity":"wellness"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[18.777996,99.037195]}}
{"type": "Feature","properties":{"title":"Amangiri","rank":9,"activity":"wellness"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[37.0146002,-111.6112931]}}
{"type": "Feature","properties":{"title":"Atacama Desert","rank":8,"activity":"desert"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-23.8634189,-69.1328491]}}
{"type": "Feature","properties":{"title":"Op een kameel door de Sinaï","rank":8,"activity":"desert"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[29.6699787,34.6331227]}}
{"type": "Feature","properties":{"title":"Ramon Crater","rank":7,"activity":"desert"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[30.6152797,34.8844867]}}
{"type": "Feature","properties":{"title":"Petra","rank":1,"activity":"desert"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[30.3284544,35.4443622]}}
{"type": "Feature","properties":{"title":"Ga offline in de Gobi woestijn","rank":8,"activity":"desert"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[42.59,103.43]}}
{"type": "Feature","properties":{"title":"Overnacht onder de sterren in de woestijn van Marokko","rank":8,"activity":"desert"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[30.44867368,-5.80078125]}}
{"type": "Feature","properties":{"title":"Huanglong","rank":8,"activity":"wonders"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[35.584467,109.840373]}}
{"type": "Feature","properties":{"title":"Hanging Monastery","rank":7,"activity":"wonders"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[39.6328955,113.7428516]}}
{"type": "Feature","properties":{"title":"Ciudad Perdida","rank":7,"activity":"wonders"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[10.7,-74.2166]}}
{"type": "Feature","properties":{"title":"Caño Cristales","rank":8,"activity":"wonders"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[2.2817466,-73.7862486]}}
{"type": "Feature","properties":{"title":"Noorderlicht","rank":8,"activity":"wonders"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[64.052222,-16.360278]}}
{"type": "Feature","properties":{"title":"Living Bridges","rank":8,"activity":"wonders"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[25.237364,91.679573]}}
{"type": "Feature","properties":{"title":"Kelimutu craters","rank":8,"activity":"wonders"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-8.7689165,121.8221085]}}
{"type": "Feature","properties":{"title":"Kawah Ijen","rank":1,"activity":"wonders"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-8.0575,114.2413889]}}
{"type": "Feature","properties":{"title":"Waw an Namus","rank":8,"activity":"wonders"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[24.916667,17.766667]}}
{"type": "Feature","properties":{"title":"Fluoriserend plankton","rank":8,"activity":"wonders"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[1.977247,73.5361034]}}
{"type": "Feature","properties":{"title":"Noorderlicht","rank":9,"activity":"wonders"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[69.666667,18.933333]}}
{"type": "Feature","properties":{"title":"Chocolate Hills","rank":7,"activity":"wonders"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[9.8499911,124.1435427]}}
{"type": "Feature","properties":{"title":"Finca Mi Universo Zip Line","rank":7,"activity":"zipline"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[3.4685972,-76.5298362]}}
{"type": "Feature","properties":{"title":"Canyoning","rank":8,"activity":"zipline"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[10.2749682,-84.8255097]}}
{"type": "Feature","properties":{"title":"The Gibbon Experience","rank":8,"activity":"zipline"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[20.262817,100.4340367]}}
{"type": "Feature","properties":{"title":"Toro Verde Nature Adventure Park","rank":1,"activity":"zipline"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[18.2565677,-66.3898444]}}
{"type": "Feature","properties":{"title":"Sun City","rank":1,"activity":"zipline"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[-25.34608,27.09723]}}
{"type": "Feature","properties":{"title":"Icy Strait Point","rank":1,"activity":"zipline"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[58.1292322,-135.4629785]}}
{"type": "Feature","properties":{"title":"Parc et Lac de Daumesnil, Parijs","rank":1,"activity":"museum"},"geometry":{"type":"Point","coordinates":[},"geometry":{"type":"Point","coordinates":[48.8324916,2.4123943]}}
]};
